---
# vars file for tomcat
  tomcat: {7.0.82: 'http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz', 8.5.9: 'http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz', 9.0.2: 'http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.2/bin/apache-tomcat-9.0.2.tar.gz'}
  tomcat_version: "{{tomcat.keys()[1]}}"
  tomcat_home: /opt/tomcat/{{tomcat_version}}
  tomcat_user: tomcat_as
  tomcat_group: tomcat_as_group
  http_port: 8080
  https_port: 8443

